### PR TITLE
Fix concurrency issue in DataSketches metrics provider

### PR DESCRIPTION
**Pull request by merlimat**
FIx for concurrency issue across threads sending the metrics values and the thread that is swapping active and replacement when doing the collection. 

Fixes yahoo/pulsar#258

### CODE REVIEW

**Comment by rdhabalia** [comment]
@merlimat we need to cherry-pick this commit to internal repo so, it can build the jars. and once jars are built then we need to cherry-pick jar-commit to this repo(mvn-repo branch) so, it can be available in our public-repo. right?
+@revans2

**Comment by revans2** [comment]
@merlimat The change looks OK, I'll try to pull this in.

**Comment by revans2** [comment]
@merlimat I managed to merge this in.  Thanks for the contribution.

**Comment by merlimat** [comment]
@revans2 Thanks, I'll update pom on pulsar repo to pick up this bk version. On the front of the 64bit ledger generation, that should be a smooth change, right?
Can there be any risk in case of "rolling back to previous version"?

**Comment by revans2** [comment]
@merlimat The 64 bit ledger ID generation should be totally backwards compatible until the ledger IDs roll over in ZK.  At that point you cannot go back, but you would be in trouble without the change anyways.

**Comment by merlimat** [comment]
Sounds great, so no worries for "ordinary" users :)

**Pull request merged**
