### PR TITLE
Update to rocksbd-5.3.6 to fix a problem in the rocksdb jni wrapper

### PR DESCRIPTION
**Pull request by merlimat**

### CODE REVIEW

**Comment by revans2** [comment]
@merlimat you have a lot more experience with rocksdb than I do.  Could you take a look at https://github.com/facebook/rocksdb/issues/2472? I found it while trying to make a release with this change in it and it scares me enough that I am tempted to revert this pull request, but I wanted to hear from you first.

**Comment by merlimat** [comment]
@revans2 The change you mentioned in the rocksdb issue it's very large and it's difficult to understand all the implications of it. 

The only difference I see, when running with `DEBUG=0` is that is not passing the `-Xcheck:jni` to the JVM, though I don't understand how could that "prevent" the error from happening.

The other possibility would be some bug in the JNI wrapper that only shows up when the optimizer is enabled.

Have you guys seen any problem related to this when running the bookies? 
I can run some tests locally as well to try to debug it.

**Comment by revans2** [comment]
@merlimat We have not moved to 5.3.6 yet.  I found the issue as we were preparing to do so, so I cannot say anything about production.  

The only other difference I know of is that `-Werror` and `-DNDEBUG` are added to the compilation command line.  The optimization levels are the same in each `-02`.  I was curious if you had been using this at all, and if you had done much with testing the new functionality?

**Comment by merlimat** [comment]
I only did some test some time back (with rocksdb-5.3.4) when I added the deleteRange to DbLedgerStorage. I was about to get started testing with the last 1.18 release bookies and brokers in the next few days.

**Comment by merlimat** [comment]
@revans2 One thing from your comment: you said the problem was "apparently" fixed in master in a commit that reordered the fields in `ReadOptions` and in one of the test the corruption was happening when doing the `ReadOptionsTests` in jni, so maybe the 2 things are really correlated.

**Comment by merlimat** [comment]
@msb-at-yahoo might have some idea on how the reordering might have "fixed" the issue.

**Comment by revans2** [comment]
@merlimat I figured out what the issue is.  It looks like an assertion is providing some kind of protection and DEBUG=0 disables that assertion which lets a test do bad things.

No need to revert things, but it might be good going forward to run bookies with `-ea` just to be on the safe side.

**Pull request merged**
