### PR TITLE
ISSUE #1078: use CachingStatsProvider underly PrometheusMetricsProvider

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

- add CachingStatsProvider to wrapper PrometheusMetricsProvider;
- add test verify the cache.

Master Issue: #1078

Author: Jia Zhai <zhaijia@apache.org>

Reviewers: Sijie Guo <sijie@apache.org>, Matteo Merli <mmerli@apache.org>

This closes #1081 from jiazhai/issue-1078, closes #1078

### CODE REVIEW

**Comment by sijie** [comment]
This is a cherry-pick fix for the prometheus stats provider.

/cc @merlimat @rdhabalia @revans2

**Review by merlimat — APPROVED** [review]
👍

**Review by jiazhai — APPROVED** [review]
+1

**Comment by rdhabalia** [comment]
I think one of the test-case is failing. can you please check on it.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.bookkeeper.stats.prometheus.TestPrometheusMetricsProvider
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.088 sec <<< FAILURE!

Results :

Tests in error: 
  testTwoCounters(org.apache.bookkeeper.stats.prometheus.TestPrometheusMetricsProvider): Collector already registered that provides name: testcounter
```

**Comment by sijie** [comment]
@rdhabalia I think one of the changes in apache/master is missing here. so I cherry-pick that change as well. the tests should be passing now.

**Comment by rdhabalia** [comment]
closing it as merged into internal branch.

**Pull request closed without merging**
