### PR TITLE
Double bytebuf fix

### PR DESCRIPTION
**Pull request by sschepens**

### CODE REVIEW

**Comment by sschepens** [comment]
@merlimat I don't have write permissions here, so you'll have to merge this, also make a new release :smile:

**Comment by merlimat** [comment]
I do have write access, though this needs to be merged internally at Yahoo for CI to build and publish binaries. ping @rdhabalia

**Comment by merlimat** [comment]
@rdhabalia Can you take a look at this?

**Comment by rdhabalia** [comment]
yes, I have picked up the commit in internal branch and will promote it here as soon as binaries are available.

**Comment by rdhabalia** [comment]
closing this PR as we have already merged the commit and released the artifacts.

**Pull request closed without merging**
